config/routes.rb
# encoding: utf-8

Rails.application.routes.draw do

  devise_for :users

  root to: 'articles#index'

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  resources :articles do
    member do
      put "like" =>"articles#like"
    end
    resources :comments, only: %i[create destroy]
  end

  resources :categories

  get '/404', to: "errors#not_found"
  get '/422', to: "errors#unacceptable"
  get '/500', to: "errors#internal_error"
end

app/models/article.rb
# encoding: utf-8

class Article < ApplicationRecord
  validates :title, :content, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy
  acts_as_votable
  has_many :article_attachments, dependent: :destroy
  accepts_nested_attributes_for :article_attachments
  has_many :article_categories
  has_many :categories, through: :article_categories
end

app/controllers/articles_controller.rb
# encoding: utf-8

class ArticlesController < ApplicationController
  before_action :article_params, only: [:create]
  before_action :fetch_article, only: %i[show destroy edit update like]
  before_action :authenticate_user!, only: %i[create new edit destroy update show]
  before_action :set_categories, only: [:new, :edit, :create]

  def index
    @articles = Article.includes(:user).all.order('created_at DESC')
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if @article.save
      params[:article]['article_categories']['category_id'].reject{ |cat| cat.empty? }.each do |cat_id|
        @article.article_categories.create(category_id: cat_id, article_id: @article.id)
      end
      params[:article_attachments]['image'].each do |a|
        @article.article_attachments.create!(image: a, article_id: @article.id)
      end
      flash[:notice] = 'Article Created'
      redirect_to @article
    else
      render 'new'
    end
  end

  def new
    @article = Article.new
    @article_attachment = @article.article_attachments.build
    @article_categories = @article.article_categories.build
  end

  def edit; end

  def show
    @article_attachments = @article.article_attachments.all
    @first_image = @article_attachments.first
    @categories = Category.all
    @comments = @article.comments.includes(:user).order(id: :desc)
    @user = @article.user
    @article.update_attributes(view_count: @article.view_count + 1)
    @comment = Comment.new(article: @article)
    @article_categories = @article.article_categories.includes(:category)
    similar_article_ids = ArticleCategory.fetch_similar_category_items(@article_categories, @article)
    @similar_article_objs = Article.where('id in (?)', similar_article_ids).includes(:user)
  end

  def update
    if @article.update(article_params)
      redirect_to @article
      flash[:notice] = 'Article updated'
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:notice] = 'Article Deleted'
    redirect_to root_path
  end

  def like
    @article.upvote_from current_user
    flash.now[:success] = 'like success'
    render layout: false
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :user_id, :article_categories,
                                    article_attachments_attributes: [:id, :article_id, :image])
  end

  def fetch_article
    @article = Article.find_by(id: params[:id])
  end

  def set_categories
    @categories = Category.pluck(:name, :id)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.haml
.col-md-12
  .well.well-sm
    %fieldset
      = simple_form_for @article do |f|
        = f.error_notification
        .form-group
          .row
            .col-md-10
              = f.text_field :title, required: true, class:'form-control', :placeholder => "Enter the Title"
              / %input#fname.form-control{:name => "title", :placeholder => "Enter the Title", :type => "text"}/
        .form-group
          .row
            .col-md-10
              = f.fields_for :article_categories do |p|
                = p.select(:category_id, options_for_select(@categories),{}, { :multiple => true})
        .form-group
          .row
            .col-md-10
              = f.text_area :content, required: true, class: 'form-control', rows: '7', :placeholder => "Add the contents"
              / %textarea#message.form-control{:name => "content", :placeholder => "Add the contents", :rows => "7"}
        .form-group
          .row
            .col-md-10
              = f.fields_for :article_attachments do |p|
                = p.label :image, label: 'Select multiple images'
                = p.file_field :image, :multiple => true, name: "article_attachments[image][]"
        .form-group
          =# f.button :submit
          .col-md-12.text-center
            %button.btn.btn-primary.btn-lg{:type => "submit"} Submit

app/views/articles/_links.haml
= link_to 'Cancel', root_path, class: 'btn btn-default'
- if user_signed_in?
  = link_to 'Edit', edit_article_path(@article), class: 'btn btn-success'
  - if @article.user == current_user
    = link_to 'Delete', article_path(@article), method: :delete, class: 'btn btn-danger'

app/views/articles/_similar.haml
%section.recomended-area.section
  .container
    .row
      - @similar_article_objs.each do |article|
        .col-lg-4.col-md-6
          .card.h-100
            .single-post.post-style-1
              .blog-image
                = image_tag(article.article_attachments.first.image_url.to_s)
              %a.avatar{:href => "#"}
                = image_tag(article.user.image_url)
              .blog-info
                %h4.title
                  %a{:href => "#"}
                    %b
                      = link_to article.title, article
                %ul.post-footer
                  %li
                    %a
                      .glyphicon.glyphicon-heart
                      = article.get_upvotes.size
                  %li
                    %a
                      .glyphicon.glyphicon-comment
                      = article.comments.count
                  %li
                    %a
                      .glyphicon.glyphicon-eye-open
                      = article.view_count

app/views/articles/edit.haml
.container
  .row
    %h3 Edit Article
    = render 'form'

app/views/articles/index.haml
%section.blog-area.section
  .container
    .row
      - @articles.each do |article|
        .col-lg-4.col-md-6
          .card.h-100
            .single-post.post-style-1
              .blog-image
                = image_tag(article.article_attachments.first.image_url.to_s)
              %a.avatar{:href => "#"}
                = image_tag(article.user.image_url)
              .blog-info
                %h4.title
                  %b
                    = link_to article.title, article
                %ul.post-footer
                  %li
                    %a
                      .glyphicon.glyphicon-heart
                      = article.get_upvotes.size
                  %li
                    %a
                      .glyphicon.glyphicon-comment
                      = article.comments.count
                  %li
                    %a
                      .glyphicon.glyphicon-eye-open
                      = article.view_count
    %a.load-more-btn{:href => "#"}
      %b LOAD MORE

app/views/articles/like.js.haml
:plain
  $('#wiki-alerts').html("#{escape_javascript (render partial: 'shared/alerts')}");
  $('#like-count').html("#{@article.get_upvotes.size}");

app/views/articles/new.haml
.container
  .row
    %h3 Create new Post
    = render 'form'

app/views/articles/show.haml
.slider
%section.post-area
  .container
    .row
      .col-lg-1.col-md-0
      .col-lg-10.col-md-12
        .main-post
          .post-top-area
            %h5.pre-title
              =# @article.category.name
            %h3.title
              %a{:href => "#"}
                %b
                  = @article.title
            .post-info
              .left-area
                %a.avatar{:href => "#"}
                  = image_tag(@user.image_url.to_s)
              .middle-area
                %b
                  = @user.user_name
                %h6.date
                  on
                  = @article.created_at.strftime('%b %d, %Y at %I:%M %p')
              .right-area
                = link_to edit_article_path(@article) do
                  .like-button
                    = image_tag('edit_article.png', alt: 'edit article')
                = link_to like_article_path(@article), method: :put , remote: :true, class: 'like-post' do
                  .like-button
                    = image_tag('like.png',alt: 'like me')
            / post-info
            %p.para
              = @article.content.split('.')[0..2].join('.')
          / post-top-area
          #myCarousel.carousel.slide{"data-ride" => "carousel",  "data-interval" => '2000' }
            / Indicators
            %ol.carousel-indicators
              - @article_attachments.each_with_index do|image, index|
                %li{"data-slide-to" => "#{index}", "data-target" => "#myCarousel", class: "#{index}" == 0 ? 'active' : ''}
            / Wrapper for slides
            .post-image
              .carousel-inner
                - @article_attachments.each_with_index do|image, index|
                  %div{:class => "item #{index == 0 ? 'active' : ''}"}
                    = image_tag(image.image_url.to_s)
              / Left and right controls
            %a.left.carousel-control{"data-slide" => "prev", :href => "#myCarousel"}
              %span.glyphicon.glyphicon-chevron-left
              %span.sr-only Previous
            %a.right.carousel-control{"data-slide" => "next", :href => "#myCarousel"}
              %span.glyphicon.glyphicon-chevron-right
              %span.sr-only Next

          .post-bottom-area
            %p.para
              = @article.content.split('.')[3..@article.content.length].join('.')
              %ul.tags
                - @article_categories.each do |article_category|
                  %li
                    %a
                      = article_category.category.name
            .post-icons-area
              %ul.post-footer
                %li
                  .glyphicon.glyphicon-heart
                  #like-count
                    = @article.get_upvotes.size
                %li
                  .glyphicon.glyphicon-comment
                  #comment-count
                    = @article.comments.count
                %li
                  .glyphicon.glyphicon-eye-open
                  #view-count
                  = @article.view_count
              %ul.icons
                %li
                  = social_share_button_tag(@article.title)
            .post-footer.post-info
              .left-area
                %a.avatar{:href => "#"}
                  = image_tag(@article.user.image_url.to_s)
              .middle-area
                %a.name{:href => "#"}
                  %b
                    = @user.user_name
                %h6.date
                  on
                  = @article.created_at.strftime('%b %d, %Y at %I:%M %p')
              .right-area
                = link_to edit_article_path(@article) do
                  .like-button
                    = image_tag('edit_article.png', alt: 'edit article')
                = link_to like_article_path(@article), method: :put , remote: :true, class: 'like-post' do
                  .like-button
                    = image_tag('like.png',alt: 'like me')
            / post-info
          / post-bottom-area
        / main-post
      / col-lg-8 col-md-12
    / row
  / container
/ post-area

= render 'similar'
%section.comment-section.center-text
  .container
    %h4
      %b POST COMMENT
    .row
      .col-lg-2.col-md-0
      .col-lg-8.col-md-12
        .comment-form
          = simple_form_for [@article, @comment], remote: :true do |f|
            .row
              .col-sm-12
                = f.text_field :description, class: 'form-control', placeholder: 'Enter Your Comment'
              .col-sm-12
                %button#form-submit.submit-btn{:type => "submit"}
                  %b POST COMMENT
        #div_comment_show
          = render 'comments/show'
%footer
  .container
    .row
      .col-lg-4.col-md-6
        .footer-section
          %a.logo{:href => "#"}
            = image_tag('blog.png', { style: 'width:100px;' })
          %p.copyright blog @ 2017. All rights reserved.
          %p.copyright
            Developed by
            = link_to 'Anoob K Bava', "http://anoobbava.github.io/about"
          %ul.icons
            %li
              %a{:href => "#"}
                %i.ion-social-facebook-outline
            %li
              %a{:href => "#"}
                %i.ion-social-twitter-outline
            %li
              %a{:href => "#"}
                %i.ion-social-instagram-outline
            %li
              %a{:href => "#"}
                %i.ion-social-vimeo-outline
            %li
              %a{:href => "#"}
                %i.ion-social-pinterest-outline
        / footer-section
      / col-lg-4 col-md-6
      .col-lg-4.col-md-6
        .footer-section
          %h4.title
            %b CATAGORIES
          %ul
            - @categories.each do |category|
              %li
                %a{:href => "#"}
                  = category.name
        / footer-section
      / col-lg-4 col-md-6
      .col-lg-4.col-md-6
        .footer-section
          %h4.title
            %b SUBSCRIBE
          .input-area
            %form
              %input.email-input{:placeholder => "Enter your email", :type => "text"}/
              %button.submit-btn{:type => "submit"}
                %i.icon.ion-ios-email-outline
        / footer-section
      / col-lg-4 col-md-6
    / row
  / container