config/routes.rb
# encoding: utf-8

Rails.application.routes.draw do

  devise_for :users

  root to: 'articles#index'

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  resources :articles do
    member do
      put "like" =>"articles#like"
    end
    resources :comments, only: %i[create destroy]
  end

  resources :categories

  get '/404', to: "errors#not_found"
  get '/422', to: "errors#unacceptable"
  get '/500', to: "errors#internal_error"
end

app/views/shared/_alerts.html.haml
#wiki-alerts
  - flash.each do |type, message|
    = js add_gritter(message, title: "#{type.capitalize}!", sticky: false, time: 1000, class_name: gritter_class_for(type))

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-default.font_family
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar
        %li= link_to 'Articles', articles_path
        - if user_signed_in?
          %li= link_to 'New Article', new_article_path
          %li= link_to 'New Category', new_category_path, data:{ modal: true }
          %li= link_to 'Category Management', categories_path
      %ul.nav.navbar-nav.pull-right
        - if user_signed_in?
          = render partial: 'layouts/notifications'
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :role => "button"}
            / The Profile picture inserted via div class below, with shaping provided by Bootstrap
            .img-rounded.profile-img
              - if user_signed_in?
                = image_tag(current_user.image_url.to_s)
              - else
                = image_tag('default.png')
            - if user_signed_in?
              = current_user.user_name
            - else
              User Name
            %span.caret
          %ul.dropdown-menu
            - if user_signed_in?
              %li
                = link_to 'Profile', edit_user_registration_path(current_user)
              %li
                = link_to 'Logout', destroy_user_session_path, method: :delete
            - else
              %li
                = link_to 'Login', new_user_session_path
              %li
                = link_to 'Signup', new_user_registration_path