config/routes.rb
# encoding: utf-8

Rails.application.routes.draw do

  devise_for :users

  root to: 'articles#index'

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  resources :articles do
    member do
      put "like" =>"articles#like"
    end
    resources :comments, only: %i[create destroy]
  end

  resources :categories

  get '/404', to: "errors#not_found"
  get '/422', to: "errors#unacceptable"
  get '/500', to: "errors#internal_error"
end

app/models/category.rb
# encoding: utf-8

class Category < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/controllers/categories_controller.rb
# encoding: utf-8

class CategoriesController < ApplicationController
  before_action :fatch_category, only: [:edit, :show, :update, :destroy]
  before_action :permit_params, only: [:create]
  respond_to :html, :json

  def new
    @category = Category.new
    respond_modal_with @category
  end

  def create
    @category = Category.new(permit_params)
    if @category.save
      flash[:notice] = 'Category created'
      respond_modal_with @category, location: root_path
    end
  end

  def update
    if @category.update(permit_params)
      redirect_to categories_path
      flash[:notice] = 'Article Updated'
    end
  end

  def destroy
    if @category.destroy
      redirect_to categories_path
      flash[:notice] = 'Category Deleted'
    end
  end

  def edit
  end

  def show
  end

  def index
    @categories = Category.all.order('created_at DESC')
  end


  private

  def permit_params
    params.require(:category).permit(:name, :description)
  end

  def fatch_category
    @category = Category.find(params[:id])
  end
end

app/views/categories/_form.html.haml
.container-fluid
  .row
    .col-md-12
      .panel.panel-login
        .panel-heading
          .row
            .col-xs-12
              %a#register-form-link{:href => "#"} Create Category
          %hr/
        .panel-body
          .row
            .col-md-12
              #register-form
                = simple_form_for(@category, remote: request.xhr?, html: { data: { modal: true } }) do |f|
                  = f.error_notification
                  .form-inputs
                    = f.input :name, label: 'Category name'
                    = f.input :description, label: 'A Brief Description about Category'
                  .form-group
                    .row
                      .col-sm-6.col-sm-offset-3
                        %input#register-submit.form-control.btn.btn-register{:name => "register-submit", :tabindex => "4", :type => "submit", :value => "create cateogory"}/

app/views/categories/edit.haml
.container-fluid
  .row
    .col-md-8
      = simple_form_for @category do |f|
        = f.input :name, value: @category.name
        = f.input :description, value: @category.description
        = f.submit

    .col-md-4

app/views/categories/index.haml
.container
  %h3 Category Management
  .category_table
    %table.table.table-bordered
      %thead
        %tr
          %th Name
          %th Description
          %th Action
      %tbody
        - @categories.each do |category|
          %tr
            %td #{category.name}
            %td #{category.description}
            %td
              = link_to edit_category_path(category) do
                .glyphicon.glyphicon-edit
              &nbsp;
              = link_to category_path(category), data: {confirm: 'Are You Sure ?'}, method: :delete, tooltip: 'delete' do
                .glyphicon.glyphicon-trash

app/views/categories/new.html.haml
= render 'form'

app/views/categories/show.html.haml
%h3
  printed new category